/* Prototype controller. Economy stays independent of rendering and audio. */
(function(){
'use strict';
const G=window.ResonanceGame,$=id=>document.getElementById(id);
const colors={bloom:'#b0e8db',string:'#dfb3ee',bell:'#f4ce9e',pulse:'#e7aebf',pad:'#a6bfee'};
const icons={bloom:'◌',string:'≋',bell:'◇',pulse:'◎',pad:'∿'};
const names={bloom:'Bloom',string:'Strings',bell:'Bells',pulse:'Pulse',pad:'Atmosphere'};
const roles={bloom:'Rounded tones · tap & hold',string:'Plucked harmonics · sweep',bell:'Shimmering overtones · scatter',pulse:'Soft percussion · tap a rhythm',pad:'Sustained chords · hold & drift'};
const descriptions={bloom:'Give your first sound a life of its own.',string:'A thread of melody woven between the blooms.',bell:'Small points of light above the ensemble.',pulse:'A gentle heartbeat beneath everything.',pad:'A slow-moving sky for your sounds to live in.'};
const worldCopy={awakening:{heading:'A little sound.<br>A world beginning.',name:'Awakening',color:'#b0e8db',description:'Five notes, open space. A simple palette with room to wander.',character:'D MAJOR PENTATONIC'},current:{heading:'Find the movement.<br>Follow the current.',name:'The Current',color:'#dfb3ee',description:'A minor colour with a bright sixth. The phrases begin to lean and sway.',character:'D DORIAN'},radiance:{heading:'Let it open.<br>There is more sky.',name:'Radiance',color:'#f4ce9e',description:'A raised fourth gives familiar tones a different edge. Explore the light between them.',character:'G LYDIAN'}};
let state=G.initial(),awake=false,starting=null,speed=1,modified=false,playing=true,muted=false,volume=.65,density=.65,tempo=72,root=50;
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,activeTab='voices',toastTimer,arrivalTimer,confirmAction=null;
let lastTick=Date.now(),knownWorlds=new Set(['awakening']),lastManualPoint=null,lastManualTime=0;
const audio=new ResonanceAudio(event=>{stage.flash(event.voice,event.degree,event.velocity,event.automatic,(!event.automatic&&performance.now()-lastManualTime<100)?lastManualPoint:null);});
const stage=new ResonanceStage($('stage'),gesture);
const fmt=(v,precision=1)=>!Number.isFinite(v)?'—':v>=1e9?(v/1e9).toFixed(2)+'b':v>=1e6?(v/1e6).toFixed(2)+'m':v>=10000?(v/1000).toFixed(1)+'k':v>=1000?Math.floor(v).toLocaleString('en-US'):Number(v.toFixed(precision)).toLocaleString('en-US');
const costText=v=>fmt(v,0);
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3300);}
function markModified(){modified=true;$('modified').hidden=false;}
function syncAudio(){audio.setConfig({bpm:tempo,root,mode:G.WORLDS.find(w=>w.id===state.world).mode,levels:state.levels,density,volume,muted,playing:playing&&awake});stage.configure(state.levels,awake,worldCopy[state.world].color,reduced);}
async function awaken(){if(awake){if(audio.getDiagnostics().contextState==='suspended')await audio.start();return true;}if(starting)return starting;starting=(async()=>{try{await audio.start();awake=true;$('start-prompt').hidden=true;$('stage-hint').textContent='Tap a bloom. Sweep a string. Hold a sound and let it drift.';syncAudio();render();return true;}catch(e){$('stage-hint').textContent='Sound could not start. Tap “Touch to awaken” to retry.';toast('Sound is unavailable here. Try opening this page in Chrome or Safari.');return false;}finally{starting=null;}})();return starting;}
async function gesture(e){if(e.kind==='release'){audio.release(e.id);return;}if(e.voice!=='bloom'&&!state.levels[e.voice])return;if(!awake){if(!await awaken())return;}
 if(e.kind==='move'){audio.moveHold(e.id,e.degree,.6);return;}
 if(e.kind==='hold'){if(stage.pointers.has(e.id))audio.hold(e.id,e.voice,e.degree);return;}
 if(e.kind==='charge'){G.tap(state,.35);stage.flash(e.voice,e.degree,.13,false,e);renderNumbers();return;}
 lastManualPoint=e;lastManualTime=performance.now();audio.play(e.voice,e.degree,e.kind==='sweep'?.45:.65,e.voice==='pad'?2:.9);G.tap(state,e.kind==='sweep'?.7:1);render();}
function voiceRate(v){const n=state.levels[v.id];return n*v.baseRate*(n>=5?2:1)*(n>=10?2:1)*(n>=25?2:1)*(1+state.upgrades.ensemble*.12)*(1+state.legacy*.03);}
function initCards(){
 $('voice-shop').innerHTML=G.VOICES.map(v=>`<article class="voice-card" id="card-${v.id}" style="--voice-color:${colors[v.id]}"><div class="voice-card-top"><span class="voice-emblem" aria-hidden="true">${icons[v.id]}</span><div class="voice-title"><h3>${names[v.id]}</h3><p id="voice-rate-${v.id}">${roles[v.id]}</p></div><span class="voice-count" id="count-${v.id}">0</span></div><p class="voice-description">${descriptions[v.id]}</p><button class="buy-button" id="buy-${v.id}" data-buy="${v.id}"><span>Awaken</span><span>✧ ${v.baseCost}</span></button><div class="card-progress"><div id="afford-${v.id}"></div></div></article>`).join('');
 $('upgrade-shop').innerHTML=G.UPGRADES.map(u=>`<article class="upgrade-card"><div><h3>${u.id==='touch'?'A stronger touch':'Ensemble resonance'} <span id="upgrade-level-${u.id}"></span></h3><p>${u.id==='touch'?'+0.8 Resonance with every touch':'+12% production across all voices'}</p></div><button id="upgrade-${u.id}" data-upgrade="${u.id}"></button></article>`).join('');
 $('world-shop').innerHTML=G.WORLDS.map((w,i)=>`<article class="world-card" id="world-card-${w.id}" style="--world-color:${worldCopy[w.id].color}"><div class="world-card-top"><span>WORLD 0${i+1}</span><span>${worldCopy[w.id].character}</span></div><h3>${worldCopy[w.id].name}</h3><p>${worldCopy[w.id].description}</p><button class="secondary-button" id="enter-${w.id}" data-world="${w.id}"></button></article>`).join('');
}
function renderNumbers(){
 $('balance').textContent=fmt(state.resonance);$('rate').textContent=fmt(G.rate(state));$('tap-value').textContent=fmt(G.tapValue(state));
 const next=G.WORLDS.find(w=>state.totalEarned<w.unlockAt);
 $('next-goal').textContent=next?'Discover '+worldCopy[next.id].name:'All three worlds are open';$('goal-fraction').textContent=next?fmt(state.totalEarned,0)+' / '+fmt(next.unlockAt,0):'Keep growing';$('goal-progress').style.width=next?Math.min(100,state.totalEarned/next.unlockAt*100)+'%':'100%';
 $('legacy-badge').hidden=!state.legacy;$('legacy-badge').textContent='✦ Legacy '+state.legacy;
 $('stat-earned').textContent=fmt(state.runEarned);$('stat-taps').textContent=fmt(state.totalTaps,0);$('stat-age').textContent=Math.floor(state.elapsed/60)+'m '+Math.floor(state.elapsed%60)+'s';$('stat-legacy').textContent=state.legacy+' · +'+(state.legacy*3)+'%';$('stat-audio').textContent=!awake?'Waiting for touch':muted?'Muted · still earning':playing?'Playing':'Paused · still earning';
 $('prestige').disabled=state.runEarned<8000;$('prestige-status').textContent=state.runEarned>=8000?'Ready · next cycle adds +3% to touch and idle production':fmt(state.runEarned,0)+' / 8,000 earned this cycle';
 $('footer-status').textContent=speed!==1?'Time flows '+speed+'× faster.':G.rate(state)>0?'Your world is playing itself.':'A little world, entirely yours.';
 for(const w of G.WORLDS){if(state.totalEarned>=w.unlockAt&&!knownWorlds.has(w.id)){knownWorlds.add(w.id);toast(worldCopy[w.id].name+' is open. Explore it in Worlds.');}}
 $('world-count').textContent=G.WORLDS.filter(w=>state.totalEarned>=w.unlockAt).length+'/3';
}
function render(){renderNumbers();for(const v of G.VOICES){const n=state.levels[v.id],price=G.cost(state,v.id),locked=state.totalEarned<v.unlockAt;const btn=$('buy-'+v.id);btn.disabled=!G.canBuy(state,v.id);btn.setAttribute('aria-label',(n?'Grow ':'Awaken ')+names[v.id]+' for '+price+' Resonance');btn.children[0].textContent=locked?'Discover at '+fmt(v.unlockAt,0):n?'Grow '+names[v.id]:'Awaken '+names[v.id];btn.children[1].textContent='✧ '+costText(price);$('count-'+v.id).textContent=n;$('voice-rate-'+v.id).textContent=n?'+'+fmt(voiceRate(v))+' / sec · '+(n<5?(5-n)+' to first 2×':n<10?(10-n)+' to next 2×':n<25?(25-n)+' to next 2×':'8× milestone bonus'):roles[v.id];$('card-'+v.id).classList.toggle('locked',locked);$('afford-'+v.id).style.width=Math.min(100,state.resonance/price*100)+'%';document.querySelector(`[data-play="${v.id}"]`).disabled=v.id!=='bloom'&&!n;}
 for(const u of G.UPGRADES){const price=G.upgradeCost(state,u.id);$('upgrade-'+u.id).disabled=state.resonance<price||!Number.isFinite(price);$('upgrade-'+u.id).textContent=Number.isFinite(price)?'✧ '+costText(price):'Max';$('upgrade-'+u.id).setAttribute('aria-label','Upgrade '+u.name+' for '+price+' Resonance');$('upgrade-level-'+u.id).textContent=state.upgrades[u.id]?'· '+state.upgrades[u.id]:'';}
 for(const w of G.WORLDS){const b=$('enter-'+w.id),open=state.totalEarned>=w.unlockAt,current=state.world===w.id;b.disabled=!open||current;b.textContent=current?'You are here':open?'Enter '+worldCopy[w.id].name:'Opens at '+fmt(w.unlockAt,0)+' earned';$('world-card-'+w.id).classList.toggle('current',current);}
}
async function buy(id){if(!G.canBuy(state,id))return{ok:false,message:'Not enough Resonance or voice not discovered.'};await awaken();const result=G.buy(state,id);if(result.ok){syncAudio();audio.play(id,0,.6,1.4);stage.flash(id,0,.9);const n=state.levels[id];toast(n===1?names[id]+' awakened. It now plays and earns on its own.':[5,10,25].includes(n)?names[id]+' ×'+n+' · production doubled!':names[id]+' grew to '+n+'.');render();}return result;}
function applyWorld(id,announce=true){const result=G.setWorld(state,id);if(!result.ok)return result;const w=G.WORLDS.find(w=>w.id===id),copy=worldCopy[id];tempo=w.bpm;root=w.root;$('tempo').value=tempo;$('tempo-value').textContent=tempo+' BPM';$('root').value=root;document.documentElement.style.setProperty('--accent',copy.color);$('world-index').textContent='WORLD 0'+(G.WORLDS.indexOf(w)+1)+' / '+copy.name.toUpperCase();$('world-heading').innerHTML=copy.heading;updateScaleLabel();syncAudio();render();if(announce){$('world-arrival').textContent=copy.name;$('world-arrival').classList.add('visible');clearTimeout(arrivalTimer);arrivalTimer=setTimeout(()=>$('world-arrival').classList.remove('visible'),2100);if(awake){audio.play('bloom',0,.45,2);setTimeout(()=>audio.play('bloom',id==='radiance'?3:5,.35,2),330);}}return result;}
function updateScaleLabel(){const n={48:'C',50:'D',52:'E',53:'F',55:'G',57:'A'}[root]||'D';$('scale-label').textContent=n+' '+G.WORLDS.find(w=>w.id===state.world).mode;}
function selectTab(tab){if(!['voices','worlds','tinker'].includes(tab))return;activeTab=tab;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab));});document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!=='tab-'+tab);render();}
function confirm(title,body,action){confirmAction=action;$('confirm-title').textContent=title;$('confirm-body').textContent=body;$('confirm-dialog').showModal();}
function setScenario(which){stage.clear();state=G.initial();speed=1;document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',b.dataset.speed==='1'));if(which==='ensemble'){state.levels={bloom:5,string:3,bell:1,pulse:1,pad:1};state.resonance=600;state.totalEarned=8000;state.runEarned=8000;state.upgrades={touch:2,ensemble:1};state.world='current';}else if(which==='radiance'){state.levels={bloom:10,string:10,bell:5,pulse:3,pad:2};state.resonance=3500;state.totalEarned=18000;state.runEarned=18000;state.upgrades={touch:4,ensemble:3};state.world='radiance';}knownWorlds=new Set(G.WORLDS.filter(w=>state.totalEarned>=w.unlockAt).map(w=>w.id));lastTick=Date.now();applyWorld(state.world,false);markModified();render();toast(which==='first'?'A new beginning. Tap to make the first sound.':which==='ensemble'?'A small ensemble, ready to explore.':'Full bloom. Play with the whole world.');}
function reset(){stage.clear();state=G.initial();speed=1;modified=false;playing=true;knownWorlds=new Set(['awakening']);$('modified').hidden=true;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause music');document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',b.dataset.speed==='1'));lastTick=Date.now();applyWorld('awakening',false);toast('Fresh start. Sound and listening settings are kept.');}
function tick(){const now=Date.now(),seconds=Math.min((now-lastTick)/1000,3600);lastTick=now;if(!awake)return;if(seconds>0)G.tick(state,seconds*speed);if(!document.hidden)render();}
$('awaken').addEventListener('click',()=>gesture({kind:'tap',voice:'bloom',degree:0,x:.29,y:.47,id:'start'}));
$('voice-shop').addEventListener('click',e=>{const b=e.target.closest('[data-buy]');if(b)void buy(b.dataset.buy);});
$('upgrade-shop').addEventListener('click',e=>{const b=e.target.closest('[data-upgrade]');if(!b)return;const result=G.buyUpgrade(state,b.dataset.upgrade);if(result.ok){syncAudio();audio.play('bloom',4,.4,1);toast(b.dataset.upgrade==='touch'?'Every touch carries more Resonance.':'All voices now earn more together.');render();}});
$('world-shop').addEventListener('click',e=>{const b=e.target.closest('[data-world]');if(b)applyWorld(b.dataset.world);});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.tab)));
$('tinker-shortcut').addEventListener('click',()=>{selectTab('tinker');if(innerWidth<=760)document.querySelector('.tabs').scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});});
document.querySelectorAll('[data-play]').forEach(b=>b.addEventListener('click',()=>gesture({kind:'tap',voice:b.dataset.play,degree:Math.floor(Math.random()*6),id:'key',x:.5,y:.5})));
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||$('confirm-dialog').open||e.repeat)return;const idx=Number(e.key)-1;if(idx>=0&&idx<5){e.preventDefault();const id=G.VOICES[idx].id;if(id==='bloom'||state.levels[id])gesture({kind:'tap',voice:id,degree:idx,id:'keyboard',x:.5,y:.5});}});
$('pause').addEventListener('click',async()=>{await awaken();playing=!playing;$('pause').textContent=playing?'Ⅱ':'▷';$('pause').setAttribute('aria-label',playing?'Pause music':'Resume music');syncAudio();render();toast(playing?'Your ensemble is playing again.':'Automatic music paused. Your world still earns.');});
$('mute').addEventListener('click',()=>{muted=!muted;$('mute').textContent=muted?'♩̸':'♫';$('mute').setAttribute('aria-label',muted?'Unmute sound':'Mute sound');syncAudio();render();});
$('volume').addEventListener('input',e=>{volume=Number(e.target.value)/100;syncAudio();});$('density').addEventListener('input',e=>{density=Number(e.target.value)/100;syncAudio();});
$('motion').addEventListener('click',()=>{reduced=!reduced;$('motion').setAttribute('aria-pressed',String(reduced));$('motion').textContent=reduced?'Full motion':'Gentle motion';syncAudio();});
$('speed-controls').addEventListener('click',e=>{const b=e.target.closest('[data-speed]');if(!b)return;tick();speed=Number(b.dataset.speed);markModified();document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));render();});
$('tempo').addEventListener('input',e=>{tempo=Number(e.target.value);$('tempo-value').textContent=tempo+' BPM';markModified();syncAudio();});$('root').addEventListener('change',e=>{root=Number(e.target.value);markModified();updateScaleLabel();syncAudio();});
$('grant').addEventListener('click',()=>{state.resonance+=500;state.totalEarned+=500;state.runEarned+=500;markModified();render();toast('+500 Resonance to experiment with.');});
$('skip').addEventListener('click',()=>{tick();const r=G.tick(state,3600);markModified();render();toast('An hour passed. Your world earned '+fmt(r.earned)+' Resonance.');});
document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>confirm('Try this moment?','This replaces your current prototype run. Listening settings are kept. There is no automatic save.',async()=>{await awaken();setScenario(b.dataset.scenario);})));
$('reset').addEventListener('click',()=>confirm('Begin from silence?','This resets your progress, Legacy, and tinkering changes. Your volume and motion preferences stay as they are.',reset));
$('prestige').addEventListener('click',()=>{if(state.runEarned<8000)return;confirm('Begin a new cycle?','Your voices, upgrades, and current Resonance reset. Gain one Legacy: +3% to touch and idle earnings. Discovered worlds remain available.',()=>{stage.clear();const r=G.prestige(state);if(r.ok){applyWorld('awakening',false);render();toast('Legacy '+state.legacy+'. A new beginning, with more possibility.');}});});
$('confirm-cancel').addEventListener('click',()=>{$('confirm-dialog').close();confirmAction=null;});$('confirm-ok').addEventListener('click',()=>{const action=confirmAction;confirmAction=null;$('confirm-dialog').close();if(action)action();});$('confirm-dialog').addEventListener('cancel',()=>{confirmAction=null;});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){tick();syncAudio();}});
initCards();applyWorld('awakening',false);$('motion').textContent=reduced?'Full motion':'Gentle motion';$('motion').setAttribute('aria-pressed',String(reduced));render();const interval=setInterval(tick,150);
window.addEventListener('pagehide',()=>stage.releaseAll());window.addEventListener('beforeunload',()=>{clearInterval(interval);audio.destroy();stage.destroy();});
// Readable state and shared actions for independent checks and supported browser agents.
window.ResonancePrototype={getState:()=>JSON.parse(JSON.stringify(state)),getAudio:()=>audio.getDiagnostics(),buy,selectWorld:applyWorld,selectTab};
const context=document.modelContext;if(context?.registerTool){const life=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
 register({name:'inspect_musical_world',description:'Read Resonance, production, voices, current world and audio status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state:window.ResonancePrototype.getState(),perSecond:G.rate(state),audio:audio.getDiagnostics()})});
 register({name:'buy_musical_voice',description:'Spend earned Resonance to buy one voice, exactly like its Grow button.',inputSchema:{type:'object',properties:{voice:{type:'string',enum:G.VOICES.map(v=>v.id)}},required:['voice'],additionalProperties:false},execute:async input=>{if(!input||!G.VOICES.some(v=>v.id===input.voice))throw new Error('Unknown voice');if(!G.canBuy(state,input.voice))return{ok:false,message:'Not affordable or not discovered.'};const result=G.buy(state,input.voice);syncAudio();render();if(awake)audio.play(input.voice,0,.6,1);return{...result,resonance:state.resonance,perSecond:G.rate(state)};}});
 window.addEventListener('pagehide',()=>life.abort(),{once:true});}
})();
