/* Functional musical geometry; no external imagery or animation dependency. */
(function(){
'use strict';
const COLORS={bloom:'#b0e8db',string:'#dfb3ee',bell:'#f4ce9e',pulse:'#e7aebf',pad:'#a6bfee'};
const POS={bloom:[.29,.47],string:[.67,.43],bell:[.8,.71],pulse:[.22,.77],pad:[.51,.76]};
class ResonanceStage{
 constructor(canvas,onGesture){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onGesture=onGesture;this.notes=[];this.sparkles=[];this.pointers=new Map();this.levels={bloom:0,string:0,bell:0,pulse:0,pad:0};this.energy={bloom:0,string:0,bell:0,pulse:0,pad:0};this.awake=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.color='#b0e8db';this.time=0;this.lastFrame=0;this.width=1;this.height=1;this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas.parentElement);this.resize();this.bind();this.draw=this.draw.bind(this);this.raf=requestAnimationFrame(this.draw);}
 resize(){const r=this.canvas.getBoundingClientRect();this.width=r.width;this.height=r.height;const d=Math.min(devicePixelRatio||1,2);this.canvas.width=r.width*d;this.canvas.height=r.height*d;this.ctx.setTransform(d,0,0,d,0,0);for(const [id,p]of Object.entries(POS)){const el=document.querySelector(`[data-label="${id}"]`);if(el){el.style.left=(p[0]*100)+'%';el.style.top=(p[1]*100+12)+'%';}}}
 configure(levels,awake,color,reduced){this.levels={...levels};this.awake=awake;this.color=color;this.reduced=reduced;for(const id of Object.keys(POS)){document.querySelector(`[data-label="${id}"]`)?.classList.toggle('visible',awake&&(id==='bloom'||levels[id]>0));}}
 point(e){const r=this.canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
 hit(p){let best='bloom',distance=.2;for(const [id,xy]of Object.entries(POS)){if(id!=='bloom'&&!this.levels[id])continue;const d=Math.hypot(p.x-xy[0],p.y-xy[1]);if(d<distance){best=id;distance=d;}}return best;}
 degree(p){return Math.round(p.x*7+(1-p.y)*3)-2;}
 bind(){const c=this.canvas;c.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();c.focus({preventScroll:true});c.setPointerCapture(e.pointerId);const p=this.point(e);const voice=this.hit(p);this.pointers.set(e.pointerId,{...p,voice,start:performance.now(),last:performance.now(),holding:false,degree:this.degree(p)});this.onGesture({kind:'tap',voice,degree:this.degree(p),id:e.pointerId,...p});});
 c.addEventListener('pointermove',e=>{const prev=this.pointers.get(e.pointerId);if(!prev)return;const p=this.point(e),now=performance.now();if(Math.hypot(p.x-prev.x,p.y-prev.y)>.035&&now-prev.last>90){const voice=this.hit(p);this.onGesture({kind:'sweep',voice,degree:this.degree(p),id:e.pointerId,...p});this.pointers.set(e.pointerId,{...prev,...p,voice,last:now,degree:this.degree(p)});}else if(prev.holding){this.onGesture({kind:'move',voice:prev.voice,degree:this.degree(p),id:e.pointerId,...p});}});
 const end=e=>{const p=this.pointers.get(e.pointerId);if(!p)return;this.onGesture({kind:'release',voice:p.voice,id:e.pointerId,...p});this.pointers.delete(e.pointerId);};c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);c.addEventListener('lostpointercapture',end);window.addEventListener('blur',()=>this.releaseAll());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.releaseAll();});}
 releaseAll(){for(const [id,p]of this.pointers)this.onGesture({kind:'release',id,voice:p.voice,...p});this.pointers.clear();}
 flash(voice,degree=0,velocity=.5,automatic=false,point){const pos=point?[point.x,point.y]:POS[voice]||POS.bloom;this.energy[voice]=Math.min(1.8,(this.energy[voice]||0)+velocity);this.notes.push({x:pos[0],y:pos[1],age:0,life:automatic?2.3:3.2,color:COLORS[voice],voice,velocity,degree,automatic});if(this.notes.length>65)this.notes.shift();if(!this.reduced)for(let i=0;i<(automatic?2:7);i++){const a=Math.random()*Math.PI*2;this.sparkles.push({x:pos[0],y:pos[1],vx:Math.cos(a)*(.01+Math.random()*.025),vy:Math.sin(a)*(.01+Math.random()*.025),age:0,life:1+Math.random()*1.4,color:COLORS[voice]});}if(this.sparkles.length>160)this.sparkles.splice(0,this.sparkles.length-160);}
 clear(){this.notes=[];this.sparkles=[];this.releaseAll();}
 draw(now){this.raf=requestAnimationFrame(this.draw);const dt=Math.min((now-(this.lastFrame||now))/1000,.05);this.lastFrame=now;if(document.hidden)return;this.time+=dt;const c=this.ctx,w=this.width,h=this.height;if(!w||!h)return;c.clearRect(0,0,w,h);
 // A quiet coordinate field makes the stage legible as an instrument.
 c.fillStyle='#a6c8d00d';for(let x=28;x<w;x+=38)for(let y=28;y<h;y+=38){c.beginPath();c.arc(x,y,.7,0,Math.PI*2);c.fill();}
 const cx=w*.47,cy=h*.57,rr=Math.min(w,h)*.44;c.strokeStyle='#bedcd908';c.lineWidth=1;for(let k=0;k<3;k++){c.beginPath();c.ellipse(cx,cy,rr*(.7+k*.23),rr*(.55+k*.18),-.2,0,Math.PI*2);c.stroke();}
 // Strings between owned voices show the ensemble taking form.
 const active=Object.keys(POS).filter(id=>id==='bloom'||this.levels[id]>0);if(this.awake&&active.length>1){c.lineWidth=.6;for(let i=1;i<active.length;i++){const p=POS[active[i]],q=POS[active[i-1]];c.beginPath();c.moveTo(q[0]*w,q[1]*h);c.quadraticCurveTo((p[0]+q[0])*w/2,(p[1]+q[1])*h/2-45,p[0]*w,p[1]*h);c.strokeStyle=this.color+'12';c.stroke();}}
 for(const id of Object.keys(POS)){this.energy[id]*=Math.exp(-dt*2.8);this.drawNode(c,id,w,h);}
 this.notes=this.notes.filter(n=>{n.age+=dt;return n.age<n.life;});for(const n of this.notes){const k=n.age/n.life,alpha=(1-k)*(n.automatic?.3:.55);c.globalAlpha=alpha;c.strokeStyle=n.color;c.lineWidth=n.automatic?.8:1.2;const r=this.reduced?18:8+k*(n.automatic?72:120);c.beginPath();c.ellipse(n.x*w,n.y*h,r,r*(n.voice==='string'?.5:1),n.degree*.2,0,Math.PI*2);c.stroke();if(!n.automatic){c.fillStyle=n.color;c.globalAlpha=alpha*.1;c.fill();}}c.globalAlpha=1;
 this.sparkles=this.sparkles.filter(p=>{p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;return p.age<p.life;});if(!this.reduced)for(const p of this.sparkles){c.globalAlpha=(1-p.age/p.life)*.7;c.fillStyle=p.color;c.beginPath();c.arc(p.x*w,p.y*h,1.4,0,Math.PI*2);c.fill();}c.globalAlpha=1;
 for(const [id,p]of this.pointers){if(now-p.start>320&&!p.holding){p.holding=true;this.onGesture({kind:'hold',voice:p.voice,degree:p.degree,id,x:p.x,y:p.y});}if(p.holding&&now-p.last>240){p.last=now;this.onGesture({kind:'charge',voice:p.voice,degree:p.degree,id,x:p.x,y:p.y});}}
 }
 drawNode(c,id,w,h){const[x,y]=POS[id],px=x*w,py=y*h;const owned=id==='bloom'||this.levels[id]>0,level=this.levels[id]||0,e=this.energy[id]||0;const base=Math.min(w,h)*.085;const r=base*(1+Math.min(level,25)*.008+e*.15);const t=this.reduced?0:this.time;const color=COLORS[id];c.save();c.translate(px,py);c.globalAlpha=owned?(this.awake?1:.72):.12;
 if(owned){const glow=c.createRadialGradient(0,0,2,0,0,r*2.6);glow.addColorStop(0,color+(e>.2?'26':'13'));glow.addColorStop(1,color+'00');c.fillStyle=glow;c.fillRect(-r*2.6,-r*2.6,r*5.2,r*5.2);}
 c.strokeStyle=color;c.lineWidth=1.1;c.fillStyle=color+'0e';
 if(id==='bloom'){for(let layer=2;layer>=0;layer--){c.beginPath();for(let i=0;i<=100;i++){const a=i/100*Math.PI*2;const z=r*(1+layer*.13)*(1+.075*Math.sin(a*3+t*.65)+.035*Math.cos(a*5-t*.5));const xx=Math.cos(a)*z,yy=Math.sin(a)*z;i?c.lineTo(xx,yy):c.moveTo(xx,yy);}c.closePath();c.globalAlpha*=layer===0?1:.65;c.fill();c.stroke();}c.fillStyle=color;c.beginPath();c.arc(0,0,3+e*2,0,Math.PI*2);c.fill();}
 if(id==='string'){c.rotate(-.18);const n=5+Math.min(3,Math.floor(level/5));for(let i=0;i<n;i++){const x=(i-(n-1)/2)*9;c.beginPath();c.moveTo(x,-r*1.1);c.bezierCurveTo(x+Math.sin(t*18+i)*e*25,-r*.35,x-Math.sin(t*18+i)*e*20,r*.35,x,r*1.1);c.stroke();}c.strokeStyle=color+'55';c.beginPath();c.ellipse(0,0,r*.96,r*1.45,0,0,Math.PI*2);c.stroke();}
 if(id==='bell'){c.rotate(.3+Math.sin(t*.5)*.06);for(let i=0;i<3;i++){c.beginPath();const z=r*(.6+i*.28);c.moveTo(0,-z);c.lineTo(z*.68,0);c.lineTo(0,z);c.lineTo(-z*.68,0);c.closePath();c.fill();c.stroke();}c.fillStyle=color;c.beginPath();c.arc(0,0,2.5+e*2,0,Math.PI*2);c.fill();}
 if(id==='pulse'){for(let i=0;i<3;i++){c.beginPath();c.ellipse(0,0,r*(.5+i*.25)+Math.sin(t*2)*e*6,r*(.5+i*.25),0,0,Math.PI*2);c.stroke();}c.fillStyle=color+'28';c.beginPath();c.arc(0,0,r*.38*(1+e*.3),0,Math.PI*2);c.fill();}
 if(id==='pad'){for(let j=0;j<5;j++){c.beginPath();for(let i=0;i<=50;i++){const xx=(i/50-.5)*r*2.6,yy=Math.sin(i/50*Math.PI*2+t*.5+j*.55)*r*.2+(j-2)*7;i?c.lineTo(xx,yy):c.moveTo(xx,yy);}c.globalAlpha*=.88;c.stroke();}}
 c.restore();}
 destroy(){cancelAnimationFrame(this.raf);this.observer.disconnect();this.releaseAll();}
}
window.ResonanceStage=ResonanceStage;
})();
